version: '2'

services:
  syncthing:
    image: joeybaker/syncthing
    restart: always
    ports:
      - "9000:8080"
      - "22000:22000"
      - "21027:21027/udp"
    volumes:
      - "./config:/srv/config"
      - "./data:/srv/data/"
